version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bank-network

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "7001:7001"
      - "7002:7002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7001;https://+:7002
    depends_on:
      - rabbitmq
    networks:
      - bank-network

  credit-proposal-service:
    build:
      context: ./CreditProposalService
      dockerfile: Dockerfile
    container_name: credit-proposal-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - bank-network

  credit-card-service:
    build:
      context: ./CreditCardService
      dockerfile: Dockerfile
    container_name: credit-card-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - bank-network

volumes:
  rabbitmq_data:

networks:
  bank-network:
    driver: bridge
